# permissions for end users to edit proxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: proxy-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ray-automl
    app.kubernetes.io/part-of: ray-automl
    app.kubernetes.io/managed-by: kustomize
  name: proxy-editor-role
rules:
- apiGroups:
  - automl.my.domain
  resources:
  - proxies
  verbs:
  - '*'
- apiGroups:
  - automl.my.domain
  resources:
  - proxies/status
  verbs:
  - get
