name: Bug report
title: "[Bug] "
description: Problems and issues with code of Ray
labels: [bug, triage]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for finding the time to report the problem! We really appreciate the community efforts to improve Ray.
        Please make sure what you are reporting is indeed a bug with reproducible steps, if you want to ask questions
        or share ideas, pleae post on our [Discussion page](https://discuss.ray.io/) instead.

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please make sure to search in the [issues](https://github.com/ray-project/ray/issues) first to see
        whether the same issue was reported already.
      options:
        - label: >
            I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar
            issues.
          required: true

  - type: dropdown
    attributes:
      label: Ray Component
      description: |
        What component are you using? Ray has many subprojects, please make sure to choose the component that
        you found the bug. For third party projects, please refer to their corresponding repos.
      multiple: false
      options:
        - "Ray Core"
        - "Ray tune"
        - "Ray Serve"
        - "RLlib"
        - "Ray Clusters"
        - "Monitoring & Debugging"
        - "Dashboard"
        - "RaySGD"
        - "Others"
    validations:
      required: true

  - type: textarea
    attributes:
      label: What happened and What you expected to happen
      description: Describe what happened and What do you think went wrong.
      placeholder: >
        Please provide the context in which the problem occurred and explain what happened. beside this,
        please also explain why you think the behaviour is erroneous. It is extremely helpful if you can 
        copy and paste the fragment of logs showing the exact error messages or wrong behaviour here.

        **NOTE**: please copy and paste texts instead of taking screenshots of them for easy future search.
    validations:
      required: true

  - type: textarea
    attributes:
      label: How to reproduce
      description: >
        What should we do to reproduce the problem? If you are not able to provide a reproducible case,
        please post on our [Discussion page](https://discuss.ray.io/) instead.
      placeholder: >
        Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to 
        reproduce the issue. The snippet should have **no external library dependencies** 
        (i.e., use fake or mock data / environments).

        **NOTE**: If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else
      description: Anything else we need to know?
      placeholder: >
        How often does this problem occur? (Once? Every time? Only when certain conditions are met?)
        Any relevant logs to include? Put them here please.

  - type: checkboxes
    attributes:
      label: Are you willing to submit PR?
      description: >
        This is absolutely not required, but we are happy to guide you in the contribution process
        especially if you already have a good understanding of how to implement the fix.
      options:
        - label: Yes I am willing to submit a PR!

  - type: markdown
    attributes:
      value: "Thanks for completing our form!"