name: BUILD-RAY-WHEELS-ON-MANY-LINUX.yml

on:
  push:
    branches: [ secretflow-ray ]
  pull_request:
    branches: [ secretflow-ray ]

jobs:
  build-wheel-pipeline:
    timeout-minutes: 600
    runs-on: ubuntu-20.04
    container: 'quay.io/pypa/manylinux2014_x86_64'

    steps:
    - name: work around permission issue
      run: git config --global --add safe.directory /__w/ray/ray

    - uses: actions/checkout@v2

    - name: Install basics
      run: |
          #  apt-get update
          #  apt-get install -yq wget curl gcc g++ openjdk-8-jdk maven zlib1g-dev zip git

    # - name: Install bazel
    #   run: |
    #        sh -c "bash ci/env/install-bazel.sh"

    - name: Install Ray and export dist
      run: |
           set -e
           set -x
           pip install -e ./python -v
           pushd ./python/ray/tests
           pytest -v test_basic.py test_basic_2.py test_actor.py 
           popd
           echo "RAN UNITTESTS SUCCESSFULLY."
